# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hap',
                'doc_host': 'https://ngenze.github.io',
                'git_url': 'https://github.com/ngenze/hap',
                'lib_path': 'hap'},
  'syms': {'hap.core': {'hap.core.foo': ('core.html#foo', 'hap/core.py')}}}
